version: 2 # use CircleCI 2.0
jobs:
  guide-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run styleguide
          command: yarn styleguide:build
      - run:
          name: Disable jekyll builds
          command: touch styleguide/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages
            git config user.email "popbaby@qq.com"
            git config user.name "supermonkeyz"
      - add_ssh_keys:
          fingerprints:
            - "5c:2e:05:c5:fb:b6:46:78:07:f6:5e:8a:b9:98:15:ec"
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dotfiles --message "[skip ci] Updates" -d styleguide


workflows:
  version: 2
  build:
    jobs:
      - guide-build