version: 2 # use CircleCI 2.0
jobs:
  guide-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run styleguide
          command: yarn styleguide:build


workflows:
  version: 2
  build:
    jobs:
      - guide-build