version: 2 # use CircleCI 2.0
jobs:
  guide-build:
    docker:
      - image: circleci/node:10
    working_directory: ~/yo-ui
    steps:
      - checkout # special step to check out source code to working directory
      - attach_workspace:
          at: ~/yo-ui
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run styleguide
          command: yarn styleguide:build
      - persist_to_workspace:
          root: .
          paths: styleguide
  guide-deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/yo-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/yo-ui
      - run:
          name: Disable jekyll builds
          command: touch styleguide/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages
            git config user.email "popbaby@qq.com"
            git config user.name "supermonkeyz"
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - add_ssh_keys:
          fingerprints:
            - "1f:f7:96:19:03:2f:8e:f3:82:e6:e5:b6:0b:1c:2d:be"
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dotfiles --message "[skip ci] Updates" -d styleguide


workflows:
  version: 2
  build:
    jobs:
      - guide-build
      - guide-deploy:
          requires:
            - guide-build
          filters:
            branches:
              only: master