/* Automatically generated by build/gen.js*/
import Device from './_util/device';
import Button from './button';
import Spinner from './spinner';

const components = {
  Button,
  Spinner
};

const YoUI = {
  install(Vue, option = {}) {
    Device.init(option.device);
    Object.keys(components).forEach(key => {
      Vue.component(components[key].name, components[key]);
    });
  }
};

// prettier-ignore
export {
  YoUI as default,
  Button,
  Spinner
};

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(YoUI);
}
